### PR TITLE
Store correct date of bucket movement

### LINKED ISSUE #240: Date of Bucket Movements always on the first of the month
Hi, is there a reason that bucket movements are always saves with the date of the first in the current month?

https://github.com/TheAxelander/OpenBudgeteer/blob/pre-release/OpenBudgeteer.Core/ViewModels/EntityViewModels/BucketViewModel.cs#L703
https://github.com/TheAxelander/OpenBudgeteer/blob/pre-release/OpenBudgeteer.Core/ViewModels/EntityViewModels/BucketViewModel.cs#L229

### PR DESCRIPTION
**Pull request by Lucaber**
fixes #240

### CODE REVIEW

**Comment by TheAxelander** [comment]
This would not work if you make a movement like for the previous month

**Comment by Lucaber** [comment]
Oh i didn't realize that this is possible

**Comment by TheAxelander** [comment]
I think the best way would be to add a month check. So if the current `YearMonth` is in the past, keep the old behavior (or use the last day of that month which would make more sense) otherwise use current date. 

What do you think?

**Comment by Lucaber** [comment]
Yes, I`m now storing the last day of the month for previous or the first day for months in the future.

**Comment by TheAxelander** [comment]
Cool, I will have a look on it and do some testings in case of any further side effects.

**Comment by TheAxelander** [comment]
Testing looking good :+1:

**Pull request merged**
