### PR TITLE
ISS143 | Target alpine

### PR DESCRIPTION
**Pull request by csillaggyujto**
Target Alpine

### CODE REVIEW

**Comment by TheAxelander** [comment]
I will test this after completion of #142 hoping that I can also fix/close #131 afterwards

**Comment by csillaggyujto** [comment]
The two PRs do not share code and can be merged independently of each other. Please test this in isolation.

**Comment by TheAxelander** [comment]
Implemented with #142

**Comment by csillaggyujto** [comment]
@TheAxelander Please reconsider merging this branch, since #142 does not contain the changes and the pre-release branch doesn't serm to have alpine support either. Targeting alpine will significantly help self-hosters, since it's a very lightweight and common base image.

**Comment by TheAxelander** [comment]
Woops, my bad. For some reason when I reviewed everything it looked like that this change was also in #142. No idea where I was looking at...
 I will follow up on #157. Sorry for that.

**Pull request closed without merging**
